### ISSUE TITLE
add to Keras

### ISSUE THREAD

**Issue by pranv** [skaae/transformer_network#1]

**Comment by skaae** [comment]
I think you should open this as a Keras issue? Feel free to copy the code as long as you write where you got i from :)

**Comment by pranv** [comment]
Sure!
I just thought that you would be able to do it faster (maybe less than an hour) than me ( studying code and transferring

**Comment by skaae** [comment]
yes. I'll open an issue in Keras, if there is interested i'll write the layer. It might also be good to have some code review + tests.

**Comment by EderSantana** [comment]
Hi, I copy pasted @skaae 's lasagne layer to a keras layer (with proper citation, but feel free to add your name or whatever you prefer to it). An example usage is here: https://github.com/EderSantana/seya/blob/master/examples/Spatial%20Transformer%20Networks.ipynb

But I tried several architectures for the localization networks (locnet in the code) but I'm not sure results look correct. If anybody is interested pls check it out and let me know what you found out.

**Comment by Victoria2333** [comment]
@skaae  Does this code have tensorflow version??
Thank you~~~
